kind: Service
apiVersion: v1
metadata:
  name: health-check-app-db-service
spec:
  selector:
    app: health-check-app-db-deployment
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: health
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer