apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiple-containers-deployment
  labels:
    app: multiple-containers-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiple-containers-app
  template:
    metadata:
      labels:
        app: multiple-containers-app
    spec:
      containers:
      - name: app1
        image: laurentiuspilca/saconf2019-e7-1:v1
        ports:
        - containerPort: 8080
      - name: app2
        image: laurentiuspilca/saconf2019-e7-2:v1
        ports:
        - containerPort: 9090